#!/bin/bash
# Regenerates THIRD_PARTY_LICENSES.md from the dependency graph that is
# ACTUALLY LINKED into the binary (go version -m on a probe build) plus the
# npm packages bundled into the frontend (Preact). Build-only tools (esbuild,
# staticcheck) are not distributed and are deliberately excluded.
#
# For each module it emits EVERY license/notice file it ships (some modules
# carry several — e.g. modernc.org/libc has LICENSE + LICENSE-3RD-PARTY.md,
# modernc.org/memory has LICENSE-GO/-MMAP-GO/-LOGO), and if none of those
# files carries a copyright line (e.g. WireGuard keeps its copyright only in
# per-file headers) it extracts one from the module's source so the notice is
# complete.
#
# Usage: scripts/gen-third-party-licenses.sh [output-path]
#   Default output THIRD_PARTY_LICENSES.md. `make notices-check` runs it to a
#   temp file and diffs, so a stale committed copy fails the build.
set -euo pipefail
# Byte-order sorting/grep everywhere so the output is identical regardless of
# the runner's locale (a UTF-8 collation would order some inputs differently).
export LC_ALL=C
cd "$(git rev-parse --show-toplevel)"

OUT=${1:-THIRD_PARTY_LICENSES.md}
MODCACHE=$(go env GOMODCACHE)
PROBE=$(mktemp)
trap 'rm -f "$PROBE"' EXIT

CGO_ENABLED=0 go build -o "$PROBE" ./cmd/ircd-web

# emit_file <path> <heading>: print a titled fenced block, GUARANTEEING a
# trailing newline before the closing fence (a license lacking a final newline
# would otherwise glue ``` onto its last line and break the Markdown).
emit_file() {
	local path=$1 heading=$2
	echo
	echo "### $heading"
	echo
	echo '```'
	cat "$path"
	[[ -n "$(tail -c1 "$path")" ]] && echo # add a newline only if the file lacks one
	echo '```'
}

# license_files <dir>: every top-level license/notice/authors file, sorted.
license_files() {
	local dir=$1
	find "$dir" -maxdepth 1 -type f \( \
		-iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \
		-o -iname 'PATENTS*' -o -iname 'AUTHORS*' -o -iname '*-LICENSE' \
		\) | sort
}

emit_module() {
	local title=$1 dir=$2
	echo
	echo "---"
	echo
	echo "## $title"
	local found=0 has_copyright=0 f
	while IFS= read -r f; do
		[[ -z "$f" ]] && continue
		found=1
		emit_file "$f" "$(basename "$f")"
		# A real copyright LINE carries a year — the MIT boilerplate phrase "the
		# above copyright notice" does not, so don't let it mask a missing notice.
		if grep -qiE 'copyright.*[12][0-9]{3}' "$f"; then has_copyright=1; fi
	done < <(license_files "$dir")
	if [[ "$found" = 0 ]]; then
		echo "ERROR: no license file found in $dir" >&2
		exit 1
	fi
	# MIT/BSD require the copyright notice; a few modules keep it only in source
	# headers (WireGuard). Surface the first such line so attribution is complete.
	if [[ "$has_copyright" = 0 ]]; then
		local cline
		# Walk the .go files in SORTED order (not grep -r's filesystem/readdir
		# order) so the "first copyright line" is deterministic across
		# environments. Modules like gvisor carry many different copyright
		# headers (varying years/authors), so an unsorted first-match would
		# differ between machines and break the notices-check gate.
		cline=$(find "$dir" -name '*.go' -type f 2>/dev/null | sort \
			| xargs -r grep -hi copyright 2>/dev/null \
			| grep -m1 -E '[12][0-9]{3}' | sed 's#^[[:space:]/*]*##' || true)
		if [[ -n "$cline" ]]; then
			echo
			echo "### Copyright (from source headers)"
			echo
			echo '```'
			echo "$cline"
			echo '```'
		fi
	fi
}

{
	echo "# Third-party licenses"
	echo
	echo "ircthing itself is licensed under the GNU AGPL-3.0-or-later (see LICENSE)."
	echo "The distributed binary statically links the Go modules below, and the"
	echo "embedded web bundle includes the npm packages below. Every license and"
	echo "notice file each module ships is reproduced here in full."
	echo
	echo "Generated by scripts/gen-third-party-licenses.sh — regenerate after any"
	echo "dependency change (\`make notices-check\` fails if this is stale); do not"
	echo "edit by hand."

	# The Go standard library and runtime are statically linked into the binary;
	# go version -m lists third-party modules but not them, so emit their license
	# (and PATENTS grant) explicitly from GOROOT.
	emit_module "Go standard library and runtime (BSD-3-Clause)" "$(go env GOROOT)"

	go version -m "$PROBE" | awk '$1=="dep"{print $2"@"$3}' | sort | while IFS= read -r mod; do
		emit_module "$mod" "$MODCACHE/$mod"
	done

	for pkg in preact; do
		dir="web/node_modules/$pkg"
		ver=$(node -p "require('./$dir/package.json').version")
		emit_module "npm: $pkg@$ver" "$dir"
	done
} >"$OUT"

echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
