#!/bin/bash
# Regenerates THIRD_PARTY_LICENSES.md from the dependency graph that is
# ACTUALLY LINKED into the binary (go version -m on a probe build) plus the
# npm packages bundled into the frontend (Preact). Build-only tools (esbuild,
# staticcheck) are not distributed and are deliberately excluded.
#
# Run after any dependency add/bump: scripts/gen-third-party-licenses.sh
# The output is committed, embedded into the binary (notices.go), and served
# at /third-party-licenses so every distributed artifact carries its notices.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

OUT=THIRD_PARTY_LICENSES.md
MODCACHE=$(go env GOMODCACHE)
PROBE=$(mktemp)
trap 'rm -f "$PROBE"' EXIT

CGO_ENABLED=0 go build -o "$PROBE" ./cmd/ircd-web

{
	echo "# Third-party licenses"
	echo
	echo "ircthing itself is licensed under the GNU AGPL-3.0-or-later (see LICENSE)."
	echo "The distributed binary statically links the Go modules below, and the"
	echo "embedded web bundle includes the npm packages below. Their license and"
	echo "copyright notices are reproduced here in full."
	echo
	echo "Generated by scripts/gen-third-party-licenses.sh — regenerate after any"
	echo "dependency change; do not edit by hand."

	go version -m "$PROBE" | awk '$1=="dep"{print $2"@"$3}' | sort | while IFS= read -r mod; do
		dir="$MODCACHE/$mod"
		lic=$(ls "$dir"/LICENSE* "$dir"/COPYING* 2>/dev/null | head -1 || true)
		if [ -z "$lic" ]; then
			echo "ERROR: no license file for $mod" >&2
			exit 1
		fi
		echo
		echo "---"
		echo
		echo "## $mod"
		echo
		echo '```'
		cat "$lic"
		echo '```'
		# Apache-2.0 requires reproducing a NOTICE file if the project ships one.
		notice=$(ls "$dir"/NOTICE* 2>/dev/null | head -1 || true)
		if [ -n "$notice" ]; then
			echo
			echo "### NOTICE"
			echo
			echo '```'
			cat "$notice"
			echo '```'
		fi
	done

	# npm packages bundled into the frontend (dependencies, not devDependencies).
	for pkg in preact; do
		dir="web/node_modules/$pkg"
		ver=$(node -p "require('./$dir/package.json').version")
		lic=$(ls "$dir"/LICENSE* 2>/dev/null | head -1 || true)
		if [ -z "$lic" ]; then
			echo "ERROR: no license file for npm package $pkg" >&2
			exit 1
		fi
		echo
		echo "---"
		echo
		echo "## npm: $pkg@$ver"
		echo
		echo '```'
		cat "$lic"
		echo '```'
	done
} >"$OUT"

echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
