// ircthing — a self-hosted, always-connected web IRC client.
// Copyright (C) 2026 AlteredParadox
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
// for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// Compact emoji shortcode table for composer tab-completion (":fire" +
// Tab). A curated common set, not a full database — the bundle budget
// matters more than long-tail coverage. Sorted by name so completion
// cycling is deterministic.
export const EMOJI = [
	["+1", "👍"],
	["-1", "👎"],
	["100", "💯"],
	["angry", "😠"],
	["arrow_down", "⬇️"],
	["arrow_up", "⬆️"],
	["art", "🎨"],
	["beer", "🍺"],
	["beers", "🍻"],
	["bell", "🔔"],
	["blush", "😊"],
	["boom", "💥"],
	["bow", "🙇"],
	["brain", "🧠"],
	["broken_heart", "💔"],
	["bug", "🐛"],
	["bulb", "💡"],
	["cake", "🍰"],
	["calendar", "📅"],
	["cat", "🐱"],
	["chart_down", "📉"],
	["chart_up", "📈"],
	["check", "✅"],
	["clap", "👏"],
	["clock", "🕐"],
	["cloud", "☁️"],
	["coffee", "☕"],
	["cold_sweat", "😰"],
	["confetti", "🎊"],
	["confused", "😕"],
	["construction", "🚧"],
	["cool", "😎"],
	["cry", "😢"],
	["crystal_ball", "🔮"],
	["dancer", "💃"],
	["dash", "💨"],
	["disappointed", "😞"],
	["dog", "🐶"],
	["door", "🚪"],
	["drum", "🥁"],
	["duck", "🦆"],
	["ear", "👂"],
	["eggplant", "🍆"],
	["eyes", "👀"],
	["facepalm", "🤦"],
	["fire", "🔥"],
	["fireworks", "🎆"],
	["fish", "🐟"],
	["fist", "✊"],
	["flushed", "😳"],
	["gear", "⚙️"],
	["ghost", "👻"],
	["gift", "🎁"],
	["grimacing", "😬"],
	["grin", "😁"],
	["hammer", "🔨"],
	["hand", "✋"],
	["handshake", "🤝"],
	["heart", "❤️"],
	["heart_eyes", "😍"],
	["hourglass", "⏳"],
	["hug", "🤗"],
	["innocent", "😇"],
	["joy", "😂"],
	["key", "🔑"],
	["kiss", "😘"],
	["laughing", "😆"],
	["lock", "🔒"],
	["mag", "🔍"],
	["melting_face", "🫠"],
	["memo", "📝"],
	["mind_blown", "🤯"],
	["money", "💰"],
	["monocle", "🧐"],
	["moon", "🌙"],
	["muscle", "💪"],
	["nail_care", "💅"],
	["nerd", "🤓"],
	["neutral_face", "😐"],
	["ninja", "🥷"],
	["no_entry", "⛔"],
	["ok_hand", "👌"],
	["party", "🥳"],
	["peace", "✌️"],
	["pensive", "😔"],
	["pizza", "🍕"],
	["point_up", "☝️"],
	["poop", "💩"],
	["popcorn", "🍿"],
	["pray", "🙏"],
	["question", "❓"],
	["rage", "😡"],
	["rainbow", "🌈"],
	["raised_hands", "🙌"],
	["robot", "🤖"],
	["rocket", "🚀"],
	["rofl", "🤣"],
	["rolling_eyes", "🙄"],
	["salute", "🫡"],
	["scream", "😱"],
	["seedling", "🌱"],
	["shipit", "🐿️"],
	["shrug", "🤷"],
	["skull", "💀"],
	["sleeping", "😴"],
	["slight_smile", "🙂"],
	["smile", "😄"],
	["smirk", "😏"],
	["snail", "🐌"],
	["sob", "😭"],
	["sparkles", "✨"],
	["star", "⭐"],
	["strong", "💪"],
	["sun", "☀️"],
	["sunglasses", "😎"],
	["sweat_smile", "😅"],
	["tada", "🎉"],
	["thinking", "🤔"],
	["thumbsdown", "👎"],
	["thumbsup", "👍"],
	["tophat", "🎩"],
	["turtle", "🐢"],
	["unamused", "😒"],
	["upside_down", "🙃"],
	["warning", "⚠️"],
	["wave", "👋"],
	["wink", "😉"],
	["wrench", "🔧"],
	["x", "❌"],
	["zap", "⚡"],
	["zzz", "💤"],
];
